name: turno
description: "smart operations"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.23+2025033101

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: 6.3.1
  flutter_localizations:
    sdk: flutter

  cupertino_icons: 1.0.6
  gradient_circular_progress_indicator: 0.0.4
  intl: any
  provider: 6.1.2
  http: 1.2.2
  shared_preferences: 2.3.2
  geolocator: 13.0.3
  permission_handler: 11.3.1
  modal_bottom_sheet: 3.0.0


dev_dependencies:

  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: 2.4.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets_dev/turno.png"
  adaptive_icon_background: "#438EFF"
  adaptive_icon_foreground: "assets_dev/turno-adaptive.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gantari
      fonts:
        - asset: assets/fonts/gantari.ttf

    - family: Icons
      fonts:
        - asset: assets/fonts/icomoon.ttf

flutter_native_splash:
  color: "#438EFF"
  image: assets/images/splash.png
  background_image: assets/images/splash.png

  android_12:
    image: assets/images/splash.png
    background_image: assets/images/splash.png
    icon_background_color: "#438EFF"

  web: false
